/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData account_circle = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData route = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData delivery = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData discover = const IconData(0xe811, fontFamily: _kFontFam);
}
